"use client";
import {useEffect,useState} from "react";
import {Flower2,Users,ShoppingBag,LogOut,Plus,RefreshCw,ShieldCheck,MessageCircle} from "lucide-react";
import {useCustomer,PinField,errors} from "@/components/customer-auth";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Sheet,SheetContent,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from "@/components/ui/alert-dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Checkbox} from "@/components/ui/checkbox";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {statuses,imageOptions,WHATSAPP,products as defaults} from "@/lib/catalog";
type Item={id:string;name?:string;quantity:number;unit?:string};
type Order={id:string;reference:string;name:string;phone:string;address:string;area:string;delivery_date:string;notes:string;items:Item[];status:typeof statuses[number];quoted_amount:number|null;created_at:string};
type Product={id:string;name:string;kn:string;description:string;description_kn:string;unit:string;unit_kn:string;category:string;image:string|null;available:boolean;guide_price:number|null};
type Customer={id:string;phone:string;name:string;created_at:string;order_count:number};
type Data={orders:Order[];products:Product[];customers:Customer[]};
const statusLabels:Record<string,string>={price_requested:"Price requested",quoted:"Quote ready",confirmed:"Confirmed",preparing:"Preparing",out_for_delivery:"Out for delivery",delivered:"Delivered",cancelled:"Cancelled"};
const money=(p:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(p/100);
const emptyProduct={id:"",name:"",kn:"",description:"",description_kn:"",unit:"molam",unit_kn:"",category:"strings",image:"/generated-mallige.webp" as string|null,available:true,guide:""};
export default function Admin(){
const {user,loading,refresh,logout}=useCustomer(),[pin,setPin]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[data,setData]=useState<Data|null>(null),[fetching,setFetching]=useState(false),[tab,setTab]=useState("orders"),[statusFilter,setStatusFilter]=useState("all"),[order,setOrder]=useState<Order|null>(null),[orderStatus,setOrderStatus]=useState<typeof statuses[number]>("price_requested"),[amount,setAmount]=useState(""),[editing,setEditing]=useState(false),[product,setProduct]=useState(emptyProduct),[confirm,setConfirm]=useState<{type:"remove_product"|"reset_pin";id:string;name:string}|null>(null),[newPin,setNewPin]=useState<{phone:string;pin:string}|null>(null);
async function load(){setFetching(true);try{const r=await fetch("/api/admin"),d=await r.json() as Data&{error?:string};if(!r.ok)throw new Error(d.error);setData(d);setError("");}catch(e){setError(errors[e instanceof Error?e.message:""]||errors.service_unavailable);}finally{setFetching(false);}}
useEffect(()=>{if(user?.role==="admin")load();else setData(null);},[user?.role]);
async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"admin_login",pin})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setPin("");await refresh();}catch(e){const code=e instanceof Error?e.message:"";setError(code==="invalid_credentials"?"Incorrect admin PIN.":errors[code]||errors.service_unavailable);}finally{setBusy(false);}}
async function mutate(body:unknown){setBusy(true);try{const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json() as {error?:string;pin?:string;phone?:string};if(!r.ok)throw new Error(d.error);await load();return d;}catch(e){toast.error(errors[e instanceof Error?e.message:""]||"The change couldn’t be saved. Try again.");return null;}finally{setBusy(false);}}
function openOrder(o:Order){setOrder(o);setOrderStatus(o.status);setAmount(o.quoted_amount?String(o.quoted_amount/100):"");}
async function saveOrder(e:React.FormEvent){e.preventDefault();if(!order)return;const d=await mutate({action:"update_order",order:{id:order.id,status:orderStatus,quoted_amount:amount?Math.round(Number(amount)*100):null}});if(d){setOrder(null);toast.success("Order updated");}}
function editProduct(p?:Product){setProduct(p?{id:p.id,name:p.name,kn:p.kn,description:p.description,description_kn:p.description_kn,unit:p.unit,unit_kn:p.unit_kn,category:p.category,image:p.image,available:!!p.available,guide:p.guide_price==null?"":String(p.guide_price/100)}:emptyProduct);setEditing(true);}
async function saveProduct(e:React.FormEvent){e.preventDefault();const {guide,...p}=product,d=await mutate({action:"save_product",product:{...p,id:p.id||undefined,guide_price:guide?Math.round(Number(guide)*100):null}});if(d){setEditing(false);toast.success("Product saved");}}
async function confirmAction(){if(!confirm)return;const d=await mutate({action:confirm.type,id:confirm.id});if(d){if(d.pin&&d.phone)setNewPin({pin:d.pin,phone:d.phone});else toast.success("Product removed from the shop");setConfirm(null);}}
const orderName=(i:Item)=>i.name||defaults.find(p=>p.id===i.id)?.name||i.id;
const orderUnit=(i:Item)=>i.unit||defaults.find(p=>p.id===i.id)?.unit||"unit";
const quotes=data?.orders.filter(o=>o.status==="price_requested").length||0,active=data?.orders.filter(o=>["confirmed","preparing","out_for_delivery"].includes(o.status)).length||0,delivered=data?.orders.filter(o=>o.status==="delivered").reduce((s,o)=>s+(o.quoted_amount||0),0)||0;
return <div className="admin-page"><Toaster/><header className="management-header"><a href="/"><img src="/logo.png" alt="NC Daily Blooms" width="115" height="72"/></a><span className="admin-brand"><ShieldCheck size={18}/> Admin</span><div><a href="/" className="text-link">View shop</a>{user?.role==="admin"&&<button className="text-link" onClick={logout}><LogOut size={17}/> Sign out</button>}</div></header>{loading?<main className="admin-main"><p>Loading…</p></main>:user?.role!=="admin"?<main className="admin-login"><span className="eyebrow">NC DAILY BLOOMS</span><h1>Admin sign in</h1><p>Manage your flowers, customers and deliveries.</p><form onSubmit={login} className="account-form"><PinField value={pin} onChange={setPin} label="Admin PIN"/>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full-width" disabled={busy||pin.length!==4}>{busy?"Signing in…":"Sign in as admin"}</button></form><small>One administrator. Customer accounts have separate access.</small></main>:<main className="admin-main"><div className="management-heading"><div><span className="eyebrow">YOUR FLOWER BUSINESS</span><h1>Manage your blooms</h1><p>Orders, daily quotes and the people you deliver to.</p></div><button className="button secondary" disabled={fetching} onClick={load}><RefreshCw size={17}/> Refresh</button></div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="admin-stats"><div><ShoppingBag/><span>Awaiting a quote</span><strong>{quotes}</strong></div><div><Flower2/><span>Active deliveries</span><strong>{active}</strong></div><div><Users/><span>Delivered order value</span><strong>{money(delivered)}</strong></div></div><Tabs value={tab} onValueChange={setTab}><TabsList className="management-tabs"><TabsTrigger value="orders">Orders</TabsTrigger><TabsTrigger value="products">Products</TabsTrigger><TabsTrigger value="customers">Customers</TabsTrigger></TabsList>
<TabsContent value="orders"><div className="panel-toolbar"><h2>Orders <span>{data?.orders.length||0}</span></h2><Select value={statusFilter} onValueChange={setStatusFilter}><SelectTrigger aria-label="Filter by order status"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{statuses.map(s=><SelectItem key={s} value={s}>{statusLabels[s]}</SelectItem>)}</SelectContent></Select></div>{!data?fetching?<p>Loading orders…</p>:<div className="management-empty"><p>Orders could not be loaded.</p><button className="button primary" onClick={load}>Try again</button></div>:!data.orders.filter(o=>statusFilter==="all"||o.status===statusFilter).length?<div className="management-empty"><ShoppingBag size={35}/><h2>No orders here yet</h2><p>New customer requests will appear here.</p></div>:<div className="admin-order-grid">{data.orders.filter(o=>statusFilter==="all"||o.status===statusFilter).map(o=><button className="admin-order-card" key={o.id} onClick={()=>openOrder(o)}><div className="order-top"><span className="order-ref">{o.reference}</span><span className={`status-tag ${o.status}`}>{statusLabels[o.status]}</span></div><h3>{o.name}</h3><p>{o.area} · {o.delivery_date}</p><span className="order-preview">{o.items.map(i=>`${orderName(i)} × ${i.quantity}`).join(", ")}</span><div className="order-total"><span>{o.quoted_amount?"Final quote":"Price request"}</span><strong>{o.quoted_amount?money(o.quoted_amount):"Set a quote"}</strong></div></button>)}</div>}<p className="small-note">Showing the latest 200 requests. Delivered value is the order total, not a payment record.</p></TabsContent>
<TabsContent value="products"><div className="panel-toolbar"><h2>Flower collection</h2><button className="button primary" onClick={()=>editProduct()}><Plus size={17}/> Add product</button></div><p className="small-note">Guide prices are for your reference. Customers receive a final quote for their request.</p><div className="management-table"><Table><TableHeader><TableRow><TableHead>Flower</TableHead><TableHead>Unit</TableHead><TableHead>Guide price</TableHead><TableHead>Availability</TableHead><TableHead>Manage</TableHead></TableRow></TableHeader><TableBody>{data?.products.map(p=><TableRow key={p.id}><TableCell><div className="product-table-name">{p.image&&<img src={p.image} alt="" width="46" height="46"/>}<span><strong>{p.name}</strong><small>{p.kn}</small></span></div></TableCell><TableCell>{p.unit}</TableCell><TableCell>{p.guide_price==null?"On enquiry":money(p.guide_price)}</TableCell><TableCell><span className={`status-tag ${p.available?"confirmed":"cancelled"}`}>{p.available?"Available":"Unavailable"}</span></TableCell><TableCell><div className="table-actions"><button className="text-link" onClick={()=>editProduct(p)}>Edit</button><button className="text-link danger" onClick={()=>setConfirm({type:"remove_product",id:p.id,name:p.name})}>Remove</button></div></TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
<TabsContent value="customers"><div className="panel-toolbar"><h2>Customer accounts <span>{data?.customers.length||0}</span></h2></div><p className="small-note">Verify the customer before resetting their PIN. A reset signs out all their sessions.</p>{!data?.customers.length?<div className="management-empty"><Users size={35}/><h2>No customer accounts yet</h2></div>:<div className="management-table"><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Mobile</TableHead><TableHead>Orders</TableHead><TableHead>Joined</TableHead><TableHead>Account access</TableHead></TableRow></TableHeader><TableBody>{data.customers.map(c=><TableRow key={c.id}><TableCell>{c.name||"New customer"}</TableCell><TableCell>{c.phone}</TableCell><TableCell>{c.order_count}</TableCell><TableCell>{c.created_at.slice(0,10)}</TableCell><TableCell><button className="text-link" onClick={()=>setConfirm({type:"reset_pin",id:c.id,name:c.phone})}>Reset PIN</button></TableCell></TableRow>)}</TableBody></Table></div>}</TabsContent></Tabs></main>}
<Sheet open={!!order} onOpenChange={v=>{if(!v&&!busy)setOrder(null);}}><SheetContent className="management-sheet"><SheetTitle>Manage order</SheetTitle><SheetDescription>{order?.reference}</SheetDescription>{order&&<div className="management-scroll"><h3>{order.name}</h3><p>+91 {order.phone}</p><p className="small-note">{order.address}<br/>{order.area}<br/>Preferred date: {order.delivery_date}</p><ul className="order-items">{order.items.map(i=><li key={i.id}><span>{orderName(i)}</span><strong>{i.quantity} × {orderUnit(i)}</strong></li>)}</ul>{order.notes&&<div className="order-note"><strong>Customer notes</strong><p>{order.notes}</p></div>}<form onSubmit={saveOrder} className="account-form"><label>Final total (₹, including delivery)<input type="number" min="0.01" max="100000" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Enter agreed total"/></label><label>Order status<Select value={orderStatus} onValueChange={v=>setOrderStatus(v as typeof statuses[number])}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{statuses.map(s=><SelectItem key={s} value={s}>{statusLabels[s]}</SelectItem>)}</SelectContent></Select></label><button className="button primary full-width" disabled={busy}>{busy?"Saving…":"Save order"}</button></form><a className="button secondary full-width" target="_blank" rel="noopener noreferrer" href={`https://wa.me/91${order.phone}?text=${encodeURIComponent(`Hi ${order.name}, NC Daily Blooms here. Regarding request ${order.reference}${order.quoted_amount?`, your final total including delivery is ${money(order.quoted_amount)}. You can confirm the quote in My Orders.`:". We’re checking today’s price and availability."}`)}`}><MessageCircle size={18}/> Contact customer on WhatsApp</a><p className="small-note">Save a quote before contacting the customer. Sending opens WhatsApp for you to review.</p></div>}</SheetContent></Sheet>
<Dialog open={editing} onOpenChange={v=>{if(!busy)setEditing(v);}}><DialogContent className="product-editor"><DialogTitle>{product.id?"Edit flower":"Add a flower"}</DialogTitle><DialogDescription>Update the collection shown in your shop.</DialogDescription><form className="account-form product-edit-form" onSubmit={saveProduct}>{([["name","Product name"],["kn","Kannada name"],["unit","Selling unit"],["unit_kn","Kannada unit"]] as const).map(([k,label])=><label key={k}>{label}<input required={k==="name"||k==="unit"} maxLength={k.includes("unit")?25:80} value={product[k]} onChange={e=>setProduct(p=>({...p,[k]:e.target.value}))}/></label>)}<label className="wide">Description<input maxLength={250} value={product.description} onChange={e=>setProduct(p=>({...p,description:e.target.value}))}/></label><label className="wide">Kannada description<input maxLength={250} value={product.description_kn} onChange={e=>setProduct(p=>({...p,description_kn:e.target.value}))}/></label><label>Category<Select value={product.category} onValueChange={v=>setProduct(p=>({...p,category:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="strings">Flower strings</SelectItem><SelectItem value="loose">Flowers & leaves</SelectItem><SelectItem value="garlands">Garlands</SelectItem></SelectContent></Select></label><label>Guide price per unit (₹)<input type="number" min="0" max="100000" step="0.01" value={product.guide} onChange={e=>setProduct(p=>({...p,guide:e.target.value}))}/></label><label className="wide">Product image<Select value={product.image||"none"} onValueChange={v=>setProduct(p=>({...p,image:v==="none"?null:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Text card</SelectItem>{imageOptions.map((i,n)=><SelectItem value={i} key={i}>{["Generated haar","Generated Mallige","Generated Sevanti","Kakada photo","Rose photo","Mixed flower photo"][n]}</SelectItem>)}</SelectContent></Select></label>{product.image&&<img className="editor-preview" src={product.image} alt="Selected product image"/>}<div className="consent wide"><Checkbox id="product-available" checked={product.available} onCheckedChange={v=>setProduct(p=>({...p,available:v===true}))}/><label htmlFor="product-available">Available for enquiries</label></div><button className="button primary wide" disabled={busy}>{busy?"Saving…":"Save product"}</button></form></DialogContent></Dialog>
<AlertDialog open={!!confirm} onOpenChange={v=>{if(!v&&!busy)setConfirm(null);}}><AlertDialogContent><AlertDialogTitle>{confirm?.type==="reset_pin"?"Reset customer PIN?":"Remove this flower?"}</AlertDialogTitle><AlertDialogDescription>{confirm?.type==="reset_pin"?`A new PIN will be generated for ${confirm.name}. Existing sessions will be signed out. Share the new PIN only after verifying the customer.`:`${confirm?.name} will be removed from the shop. Existing order details are kept.`}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();confirmAction();}}>{busy?"Please wait…":"Confirm"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
<Dialog open={!!newPin} onOpenChange={v=>{if(!v)setNewPin(null);}}><DialogContent><DialogTitle>Customer PIN reset</DialogTitle><DialogDescription>Save or share this PIN now. It is shown once.</DialogDescription>{newPin&&<div className="generated-pin"><strong>{newPin.pin}</strong><p>+91 {newPin.phone}</p><a className="button primary full-width" target="_blank" rel="noopener noreferrer" href={`https://wa.me/91${newPin.phone}?text=${encodeURIComponent(`Your NC Daily Blooms login PIN has been reset to ${newPin.pin}. Use your phone number and this PIN to sign in. Keep it private.`)}`}>Share PIN on WhatsApp</a><button className="button secondary full-width" onClick={()=>setNewPin(null)}>Done</button></div>}</DialogContent></Dialog></div>;
}
