"use client";
import {createContext,useContext,useEffect,useState} from "react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {InputOTP,InputOTPGroup,InputOTPSlot} from "@/components/ui/input-otp";
import {REGEXP_ONLY_DIGITS} from "input-otp";
export type User={subject:string;role:"customer"|"admin";phone?:string;name?:string};
const Context=createContext<{user:User|null;loading:boolean;openLogin:()=>void;refresh:()=>Promise<void>;logout:()=>Promise<void>}>({user:null,loading:true,openLogin:()=>{},refresh:async()=>{},logout:async()=>{}});
export const useCustomer=()=>useContext(Context);
export const errors:Record<string,string>={invalid_credentials:"The phone number or PIN is incorrect.",invalid_pin:"Enter a 4-digit PIN.",invalid_phone:"Enter a valid 10-digit Indian mobile number.",account_exists:"This number already has an account. Sign in with your saved PIN.",too_many_attempts:"Too many attempts. Please try again after 15 minutes.",service_unavailable:"We couldn’t complete that request. Please try again.",sign_in_required:"Please sign in to continue.",product_unavailable:"A selected flower is unavailable. Refresh your bag and try again.",quote_unavailable:"This quote has changed. Refresh your orders before confirming.",invalid_order:"Check your delivery details and preferred date.",quote_required:"Enter the final total before choosing this status."};
export function PinField({value,onChange,label="4-digit PIN"}:{value:string;onChange:(s:string)=>void;label?:string}){return <div className="pin-field"><label>{label}</label><InputOTP maxLength={4} pattern={REGEXP_ONLY_DIGITS} value={value} onChange={onChange} aria-label={label} autoComplete="off"><InputOTPGroup>{[0,1,2,3].map(i=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP></div>;}
export function CustomerProvider({children}:{children:React.ReactNode}){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[mode,setMode]=useState("login"),[phone,setPhone]=useState(""),[pin,setPin]=useState(""),[generated,setGenerated]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[kn,setKn]=useState(false);
 async function refresh(){try{const r=await fetch("/api/auth");if(r.ok){const d=await r.json() as {user:User|null};setUser(d.user);}}finally{setLoading(false);}}
 useEffect(()=>{refresh().catch(()=>setLoading(false));},[]);
 async function logout(){const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})});if(r.ok)setUser(null);}
 function openLogin(){setKn(document.documentElement.lang==="kn");setError("");setPin("");setOpen(true);}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:mode==="register"?"register":"login",phone,pin})}),d=await r.json() as {user:User;pin?:string;error?:string};if(!r.ok)throw new Error(d.error);setUser(d.user);setPin("");if(d.pin)setGenerated(d.pin);else setOpen(false);}catch(e){const code=e instanceof Error?e.message:"service_unavailable";setError(kn?(code==="account_exists"?"ಈ ಸಂಖ್ಯೆಗೆ ಖಾತೆ ಇದೆ. ನಿಮ್ಮ PIN ಬಳಸಿ ಲಾಗಿನ್ ಮಾಡಿ.":code==="too_many_attempts"?"ಹೆಚ್ಚು ಪ್ರಯತ್ನಗಳಾಗಿವೆ. 15 ನಿಮಿಷದ ಬಳಿಕ ಪ್ರಯತ್ನಿಸಿ.":"ವಿವರ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ."):(errors[code]||errors.service_unavailable));}finally{setBusy(false);}}
 return <Context.Provider value={{user,loading,openLogin,refresh,logout}}>{children}<Dialog open={open} onOpenChange={v=>{if(!generated&&!busy)setOpen(v);}}><DialogContent className="auth-dialog" showCloseButton={!generated&&!busy}><DialogTitle>{generated?(kn?"ನಿಮ್ಮ ಹೊಸ PIN":"Your new login PIN"):(kn?"ನಿಮ್ಮ ಹೂವಿನ ಖಾತೆ":"Your flower account")}</DialogTitle><DialogDescription>{generated?(kn?"ಈ PIN ಒಮ್ಮೆ ಮಾತ್ರ ತೋರಿಸಲಾಗುತ್ತದೆ. ಮುಂದಿನ ಲಾಗಿನ್‌ಗಾಗಿ ಉಳಿಸಿಕೊಳ್ಳಿ.":"This PIN is shown once. Save it for future logins with your phone number."):(kn?"ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ಮತ್ತು 4 ಅಂಕಿಯ PIN ಬಳಸಿ.":"Use your phone number and a permanent 4-digit PIN.")}</DialogDescription>{generated?<div className="generated-pin"><strong>{generated}</strong><p>{phone}</p><span>{kn?"SMS ಕಳುಹಿಸಲಾಗುವುದಿಲ್ಲ. PIN ಮರೆತರೆ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ.":"No SMS is sent. Contact us if you forget your PIN."}</span><button className="button primary full-width" onClick={()=>{setGenerated("");setOpen(false);}}>{kn?"PIN ಉಳಿಸಿಕೊಂಡಿದ್ದೇನೆ":"I’ve saved my PIN"}</button></div>:<><Tabs value={mode} onValueChange={v=>{setMode(v);setError("");}}><TabsList className="auth-tabs"><TabsTrigger value="login">{kn?"ಲಾಗಿನ್":"Sign in"}</TabsTrigger><TabsTrigger value="register">{kn?"ಹೊಸ ಖಾತೆ":"Create account"}</TabsTrigger></TabsList></Tabs><form onSubmit={submit} className="account-form"><label>{kn?"ಮೊಬೈಲ್ ಸಂಖ್ಯೆ":"Mobile number"}<div className="phone-input"><span>+91</span><input type="tel" inputMode="numeric" autoComplete="tel-national" required pattern="[6-9][0-9]{9}" maxLength={10} value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,""))}/></div></label>{mode==="login"?<PinField value={pin} onChange={setPin} label={kn?"4 ಅಂಕಿಯ PIN":"4-digit PIN"}/>:<p className="small-note">{kn?"ನಿಮಗಾಗಿ 4 ಅಂಕಿಯ PIN ರಚಿಸುತ್ತೇವೆ. ಇದನ್ನು ಉಳಿಸಿಕೊಳ್ಳಿ. ಇದು SMS ಪರಿಶೀಲನೆ ಅಲ್ಲ.":"We’ll generate your 4-digit PIN. Save it for your next login. This does not verify ownership of the phone number."}</p>}{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary full-width" disabled={busy||(mode==="login"&&pin.length!==4)}>{busy?(kn?"ದಯವಿಟ್ಟು ಕಾಯಿರಿ…":"Please wait…"):mode==="login"?(kn?"ಲಾಗಿನ್ ಮಾಡಿ":"Sign in"):(kn?"ನನ್ನ PIN ರಚಿಸಿ":"Generate my PIN")}</button>{mode==="login"&&<a href="https://wa.me/916362535373?text=I%20need%20help%20resetting%20my%20NC%20Daily%20Blooms%20PIN." className="text-link" target="_blank" rel="noopener noreferrer">{kn?"PIN ಮರೆತಿದ್ದೀರಾ? ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ":"Forgot your PIN? Contact us"}</a>}</form></>}</DialogContent></Dialog></Context.Provider>;
}
