"use client";
import {useEffect,useState} from "react";
import {CheckCircle2,LogOut,ShoppingBag} from "lucide-react";
import {useCustomer,errors} from "@/components/customer-auth";
import {WHATSAPP} from "@/lib/catalog";
type Order={id:string;reference:string;name:string;phone:string;address:string;area:string;delivery_date:string;status:string;quoted_amount:number|null;created_at:string;items:{id:string;name?:string;kn?:string;unit?:string;unitKn?:string;quantity:number}[]};
const label:Record<string,string>={price_requested:"Price requested",quoted:"Quote ready",confirmed:"Confirmed",preparing:"Preparing",out_for_delivery:"Out for delivery",delivered:"Delivered",cancelled:"Cancelled"};
const labelsKn:Record<string,string>={price_requested:"ಬೆಲೆ ವಿಚಾರಣೆ",quoted:"ಬೆಲೆ ಸಿದ್ಧವಾಗಿದೆ",confirmed:"ದೃಢವಾಗಿದೆ",preparing:"ತಯಾರಿಸಲಾಗುತ್ತಿದೆ",out_for_delivery:"ಡೆಲಿವರಿಗಾಗಿ ಹೊರಟಿದೆ",delivered:"ತಲುಪಿಸಲಾಗಿದೆ",cancelled:"ರದ್ದುಪಡಿಸಲಾಗಿದೆ"};
export default function Account(){const {user,loading,openLogin,logout}=useCustomer(),[orders,setOrders]=useState<Order[]>([]),[error,setError]=useState(""),[pending,setPending]=useState(""),[kn,setKn]=useState(false),[fetching,setFetching]=useState(true);
async function load(){setFetching(true);try{const r=await fetch("/api/account"),d=await r.json() as {orders:Order[];error?:string};if(!r.ok)throw new Error(d.error);setOrders(d.orders);setError("");}catch(e){setError(errors[e instanceof Error?e.message:""]||errors.service_unavailable);}finally{setFetching(false);}}
useEffect(()=>{setKn(localStorage.getItem("nc-language")==="kn");if(user?.role==="customer")load();else{setOrders([]);setFetching(false);}},[user?.subject,user?.role]);
async function accept(id:string){setPending(id);try{const r=await fetch("/api/account",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"accept_quote",id})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);await load();}catch(e){setError(errors[e instanceof Error?e.message:""]||errors.service_unavailable);}finally{setPending("");}}
return <div className="account-page"><header className="management-header"><a href="/"><img src="/logo.png" alt="NC Daily Blooms" width="115" height="72"/></a><a href="/" className="text-link">{kn?"ಹೂವುಗಳನ್ನು ನೋಡಿ":"Shop flowers"}</a>{user&&<button className="text-link" onClick={logout}><LogOut size={17}/>{kn?"ಲಾಗ್ ಔಟ್":"Sign out"}</button>}</header><main className="account-main"><span className="eyebrow">NC DAILY BLOOMS</span><h1>{kn?"ನನ್ನ ಆರ್ಡರ್‌ಗಳು":"My flower orders"}</h1>{loading?<p>Loading…</p>:user?.role!=="customer"?<div className="management-empty"><ShoppingBag size={40}/><h2>{kn?"ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ":"Sign in to your flower account"}</h2><p>{kn?"ಬೆಲೆ ಮತ್ತು ಡೆಲಿವರಿ ಸ್ಥಿತಿ ನೋಡಿ.":"See your price requests, quotes and delivery updates."}</p><button onClick={openLogin} className="button primary">{kn?"ಲಾಗಿನ್ / ಹೊಸ ಖಾತೆ":"Sign in / create account"}</button></div>:<><div className="account-identity"><CheckCircle2 size={19}/><span>+91 {user.phone}</span><button className="text-link" onClick={load}>{kn?"ರಿಫ್ರೆಶ್":"Refresh orders"}</button></div><p className="small-note">{kn?"ಒಟ್ಟು ಬೆಲೆ ಡೆಲಿವರಿಯನ್ನು ಒಳಗೊಂಡಿದೆ. ಇಲ್ಲಿ ಪಾವತಿ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ.":"The final quote includes delivery. No payment is collected here; arrange payment with us after confirming."}</p>{error&&<p className="form-error" role="alert">{error}</p>}{fetching?<p className="small-note">{kn?"ಆರ್ಡರ್‌ಗಳನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ…":"Loading your orders…"}</p>:!orders.length?<div className="management-empty"><ShoppingBag size={35}/><h2>{kn?"ಇನ್ನೂ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ":"Your first flowers are waiting"}</h2><a href="/#flowers" className="button primary">{kn?"ಹೂವುಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ":"Choose your flowers"}</a></div>:<div className="account-orders">{orders.map(o=><article className="order-card" key={o.id}><div className="order-top"><span className="order-ref">{o.reference}</span><span className={`status-tag ${o.status}`}>{(kn?labelsKn:label)[o.status]||o.status}</span></div><ul>{o.items.map(i=><li key={i.id}>{kn?i.kn||i.name||i.id:i.name||i.id}<span>{i.quantity} × {kn?i.unitKn||i.unit:i.unit||"unit"}</span></li>)}</ul><div className="order-meta"><span>{kn?"ಡೆಲಿವರಿ":"Delivery"}: {o.delivery_date}</span><span>{o.area}</span><p>{o.address}</p></div><div className="order-total"><span>{kn?"ಅಂತಿಮ ಒಟ್ಟು":"Final total"}</span><strong>{o.quoted_amount?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(o.quoted_amount/100):(kn?"ಬೆಲೆ ದೃಢೀಕರಿಸಬೇಕು":"Awaiting quote")}</strong></div>{o.status==="quoted"&&<button className="button primary full-width" disabled={pending===o.id} onClick={()=>accept(o.id)}>{pending===o.id?"…":kn?"ಈ ಬೆಲೆಯಲ್ಲಿ ಆರ್ಡರ್ ದೃಢೀಕರಿಸಿ":"Accept quote & confirm order"}</button>}<a className="text-link" href={`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(`Hi! I have a question about my order ${o.reference}.`)}`} target="_blank" rel="noopener noreferrer">{kn?"ಆರ್ಡರ್ ಬಗ್ಗೆ ಸಂಪರ್ಕಿಸಿ":"Ask about this order"}</a></article>)}</div>}</>}</main></div>;}
